<script setup lang="ts">
import type Privacy from '~/types/privacy';


const props = defineProps<{ privacy: Privacy | null }>();
</script>

<template>
  <section class="privacy-content">
    <ul>
      <li>
        <p>
          This text is an example of a text that can be replaced in the same
          space, this text has been generated from the Arabic text generator,
          where you can generate such text or many other texts as well as
          increase the number of letters generated by the application. If you
          need more paragraphs, the Arabic text generator allows you to increase
          the number of paragraphs as you like, the text will not appear divided
          and contains no language errors, the Arabic text generator is useful
          for website designers in particular, as the client often needs to see
          a real picture of the design of the site.
        </p>
      </li>
      <li>
        <p v-html="privacy?.privacy">

        </p>
      </li>
    </ul>
  </section>
</template>

<style scoped></style>