export function useCourseProtectionConfig() {
  return {
    enabled: true,
    blockInspectShortcuts: true,
    blockContextMenu: true,
    blockDocumentShortcuts: true,
    blockMediaDrag: true,
    blockProtectedCopy: true,
    blockProtectedWindowBlur: true,
    blockPrint: true,
    captureShield: true,
    developerToolsGuard: true,
    developerToolsOpenThresholdPx: 170,
    developerToolsCloseThresholdPx: 120,
    developerToolsOpenChecks: 3,
    developerToolsClosedChecks: 3,
    developerToolsPollIntervalMs: 500,
    shieldOnWindowBlur: true,
    watermarkEnabled: true,
    watermarkCopies: 15,
    watermarkOpacity: 0.3,
    watermarkShowStudentName: true,
    watermarkShowStudentId: true,
    watermarkShowCourseId: true,
    watermarkFallbackText: "محتوى تعليمي محمي",
    disableVideoDownload: true,
    disablePictureInPicture: true,
    disableRemotePlayback: true,
    hidePdfToolbar: true,
    pdfNoReferrer: true,
    noticeDurationMs: 2600,
    focusRestoreDelayMs: 300,
  } as const;
}
